name: Python Package using Conda

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r ./MysqlExport/requirements.txt
        
    - name: Package script
      run: |
        pyinstaller --onefile --noconsole --distpath ./MysqlExport ./MysqlExport/ExportGUI.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: packaged-script
        path: MysqlExport/
